metricbeat.config.modules:
  # Mounted `metricbeat-daemonset-modules` configmap:
  path: ${path.config}/modules.d/*.yml
  # Reload module configs as they change:
  reload.enabled: false

metricbeat.autodiscover:
  providers:
  - type: docker
    templates:
    - condition:
        equals.docker.container.image: etcd
      config:
      - module: etcd
        metricsets: ["leader", "self", "store"]
        period: 10s
        hosts: ["${host}:2379"]

metricbeat.modules:
- module: system
  period: 10s
  metricsets:
  - cpu
  - filesystem
  - fsstat
  - load
  - memory
  - network
  - process
  - process_summary
  - uptime
  - core
  - diskio
  - socket
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
- module: system
  period: 1m
  metricsets:
  - filesystem
  - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

processors:
- add_cloud_metadata:

output.streams:
  region: ap-northeast-1
  stream_name: test1
  # Use https://github.com/rs/xid to generate a unique ID per event
  partition_key_provider: xid

queue.mem:
  events: 4096
  flush.min_events: 5
  flush.timeout: 3s
