ignored = ["github.com/elastic/beats*"]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.14"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jpillora/backoff"
  version = "1.0.0"
