ignored = ["github.com/elastic/beats*"]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.14"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.1.0"
