version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build-and-push:
    executor: machine
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circle

workflows:
  build-and-push:
    jobs:
      - build-and-push:
          context: ecr

