#!/usr/bin/env bash

# https://discuss.elastic.co/t/docker-module-cant-connect-to-var-run-docker-sock/86835
docker run \
  --rm \
  -u root \
  --volume=/proc:/hostfs/proc:ro \
  --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \
  --volume=/:/hostfs:ro \
  --net=host \
  -v $(pwd)/logs:/mnt/log/ \
  -v $(pwd)/example/metricbeat:/etc/metricbeat \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  -it \
  s12v/awsbeats:metricbeat-canary \
  metricbeat \
  --plugin kinesis.so \
  -e \
  -d '*' \
  -c /etc/metricbeat/metricbeat.yml \
  --strict.perms=false \
  -system.hostfs=/hostfs

# Note that `strict.perms` seems to be required due to https://discuss.elastic.co/t/volume-mapped-filebeat-yml-permissions-from-docker-on-windows-host/91893/2
