#!/usr/bin/env bash

docker run \
  --rm \
  -v $(pwd)/logs:/mnt/log/ \
  -v $(pwd)/example/apm-server:/etc/apm-server \
  -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  s12v/awsbeats:apm-server-canary \
  apm-server \
  --plugin kinesis.so \
  -e \
  -d '*' \
  -c /etc/apm-server/apm-server.yml \
  --strict.perms=false

# Note that `strict.perms` seems to be required due to https://discuss.elastic.co/t/volume-mapped-filebeat-yml-permissions-from-docker-on-windows-host/91893/2
